name: NPCIntroductions
version: '${project.version}'
main: rama.npcintroductions.NPCIntroductions
soft-depend: [ Citizens , ServersNPC]
authors: [ ImRama ]
description: First click messages for your NPCS
commands:
  npci: